packages:
  - "apps/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "sharp"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
